"""Export the screening prompts to a LaTeX appendix.

Generated from the code that runs the screen, so the supplementary cannot drift
from what was actually sent to the models. The prompts use the ``termlist`` in
``termbox`` style defined in main.tex.
"""

from pathlib import Path

from prompts import DOMAIN_PROMPT, OUTCOME_PROMPTS, SCOPE_GUARD

SUPPLEMENTARY_DIR = Path(__file__).parent.parent.parent / "supplementary"
APPENDIX_PATH = SUPPLEMENTARY_DIR / "appendix_prompts.tex"
GENERATED_NOTE = "% Generated by code/export_prompts.py -- do not edit by hand."

OUTCOME_PROMPT_LABELS = {
    "P1_neutral": "P1 neutral",
    "P2_mechanism": "P2 mechanism",
    "P3_apriori": "P3 a priori",
    "P4_symmetry": "P4 symmetry",
    "P5_screening": "P5 screening",
}


def escape_latex(text):
    """Escape the LaTeX special characters that occur in the prompts."""
    for character, replacement in (("\\", r"\textbackslash "), ("_", r"\_"),
                                   ("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        text = text.replace(character, replacement)
    return text


def format_body(text):
    """Escape and lay out prompt text for a ttfamily group.

    Blank lines become paragraph breaks; single line breaks become explicit
    `\\\\` breaks, so a numbered list in a prompt keeps one line per item
    instead of collapsing into running text.
    """
    paragraphs = escape_latex(text).split("\n\n")
    return "\n\n".join(" \\\\\n".join(paragraph.split("\n")) for paragraph in paragraphs)


def list_item(label, body):
    """Render one termlist item with a monospace body.

    Uses a `{\\ttfamily ...}` group rather than `\\texttt{...}`: some prompts
    contain a blank line, and `\\texttt` cannot take a paragraph break inside
    its argument.
    """
    return f"\\item[{label}:] {{\\ttfamily {format_body(body)}}}"


def prompt_items():
    """Render the scope guard, outcome prompts and domain prompt as termlist items."""
    items = [list_item("Scope guard", SCOPE_GUARD)]
    items += [list_item(OUTCOME_PROMPT_LABELS[name], body)
              for name, body in OUTCOME_PROMPTS.items()]
    items.append(list_item("Domain prompt", DOMAIN_PROMPT))
    return "\n".join(items)


def boxed_list(items_text, list_options=""):
    """Wrap termlist items in the shared termbox/termlist environment."""
    return (f"\\begin{{mdframed}}[style=termbox]\n"
            f"\\begin{{termlist}}{list_options}\n{items_text}\n\\end{{termlist}}\n"
            f"\\end{{mdframed}}")


def build_appendix():
    """Assemble the appendix source."""
    parts = [
        GENERATED_NOTE,
        "\\section{Prompts}",
        "\\label{sec:appendix}",
        "",
        "This section lists the exact prompts sent to both language models "
        "(Classification).",
        "Every prompt below is preceded by the paper's title and abstract. The "
        "five outcome prompts are further preceded by the scope guard.",
        "",
        boxed_list(prompt_items(), "\\small\\raggedright"),
    ]
    return "\n".join(parts)


def main():
    """Write the generated appendix into the supplementary folder."""
    APPENDIX_PATH.write_text(build_appendix())
    print(f"wrote {APPENDIX_PATH}")


if __name__ == "__main__":
    main()
