"""Export the screening prompts and term groups to a LaTeX appendix.

Generated from the code that runs the screen, so the supplementary cannot drift
from what was actually sent to the models. Term groups and prompts share one
list style (``termlist`` in a ``termbox``, defined in main.tex) so the appendix
reads as a single unit rather than two differently formatted sections.
"""

from pathlib import Path

from prompts import DOMAIN_PROMPT, OUTCOME_PROMPTS, SCOPE_GUARD
from pubmed_scoring import PUBMED_TERM_GROUPS

SUPPLEMENTARY_DIR = Path(__file__).parent.parent.parent / "supplementary"
APPENDIX_PATH = SUPPLEMENTARY_DIR / "appendix_prompts.tex"
GENERATED_NOTE = "% Generated by code/export_prompts.py -- do not edit by hand."

TERM_GROUP_LABELS = {
    "theme": "Theme",
    "reference_model": "Reference model",
    "interaction_metric": "Interaction metric",
    "interaction_labelling": "Interaction labelling",
    "assay_design": "Assay design",
    "software": "Software",
}

OUTCOME_PROMPT_LABELS = {
    "P1_neutral": "P1 neutral",
    "P2_mechanism": "P2 mechanism",
    "P3_apriori": "P3 a priori",
    "P4_symmetry": "P4 symmetry",
    "P5_screening": "P5 screening",
}


def escape_latex(text):
    """Escape the LaTeX special characters that occur in the prompts."""
    for character, replacement in (("\\", r"\textbackslash "), ("_", r"\_"),
                                   ("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        text = text.replace(character, replacement)
    return text


def format_body(text):
    """Escape and lay out prompt text for a ttfamily group.

    Blank lines become paragraph breaks; single line breaks become explicit
    `\\\\` breaks, so a numbered list in a prompt keeps one line per item
    instead of collapsing into running text.
    """
    paragraphs = escape_latex(text).split("\n\n")
    return "\n\n".join(" \\\\\n".join(paragraph.split("\n")) for paragraph in paragraphs)


def list_item(label, body):
    """Render one termlist item with a monospace body.

    Uses a `{\\ttfamily ...}` group rather than `\\texttt{...}`: some prompts
    contain a blank line, and `\\texttt` cannot take a paragraph break inside
    its argument.
    """
    return f"\\item[{label}:] {{\\ttfamily {format_body(body)}}}"


def term_group_items():
    """Render the term-group queries as termlist items."""
    return "\n".join(list_item(TERM_GROUP_LABELS[name], query)
                     for name, query in PUBMED_TERM_GROUPS.items())


def prompt_items():
    """Render the scope guard, outcome prompts and domain prompt as termlist items."""
    items = [list_item("Scope guard", SCOPE_GUARD)]
    items += [list_item(OUTCOME_PROMPT_LABELS[name], body)
              for name, body in OUTCOME_PROMPTS.items()]
    items.append(list_item("Domain prompt", DOMAIN_PROMPT))
    return "\n".join(items)


def boxed_list(items_text, list_options=""):
    """Wrap termlist items in the shared termbox/termlist environment."""
    return (f"\\begin{{mdframed}}[style=termbox]\n"
            f"\\begin{{termlist}}{list_options}\n{items_text}\n\\end{{termlist}}\n"
            f"\\end{{mdframed}}")


def build_appendix():
    """Assemble the appendix source."""
    parts = [
        GENERATED_NOTE,
        "\\section{Search terms and prompts}",
        "\\label{sec:appendix}",
        "",
        "This section lists, in full, the PubMed queries behind each term group "
        "(Finding eligible papers) and the exact prompts sent to both language "
        "models (Classification).",
        "",
        "\\subsection{Term groups}",
        "",
        "Each group is issued as its own PubMed query.",
        "",
        boxed_list(term_group_items(), "\\small\\raggedright"),
        "",
        "\\subsection{Prompts}",
        "",
        "Every prompt below is preceded by the paper's title and abstract. The "
        "five outcome prompts are further preceded by the scope guard.",
        "",
        boxed_list(prompt_items(), "\\small\\raggedright"),
    ]
    return "\n".join(parts)


def main():
    """Write the generated appendix into the supplementary folder."""
    APPENDIX_PATH.write_text(build_appendix())
    print(f"wrote {APPENDIX_PATH}")


if __name__ == "__main__":
    main()
